### ISSUE TITLE
Issue to get dashing updated from sensu

### ISSUE THREAD

**Issue by cloareq** [mrichar1/dashing-sensu#4]
Hey,

I am trying to run your dashing-sensu plugin but I am having the following result :

```bash
scheduler caught exception:
undefined method `empty?' for #<URI::HTTP:0x000000024233b0 URL:http://localhost:4567/events>
/usr/lib/ruby/1.9.1/net/http.rb:1861:in `initialize'
/usr/lib/ruby/1.9.1/net/http.rb:2094:in `initialize'
/root/msolution.io/jobs/sensu.rb:22:in `new'
/root/msolution.io/jobs/sensu.rb:22:in `block in <top (required)>'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/var/lib/gems/1.9.1/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'
```

I am running sensu 0.17 and here is my request :

```bash
curl http://localhost:4567/events
[{"id":"581bb331-f2dd-4eb6-9f80-8cde0fbd5ba6","client":{"name":"4-C2C-Node25","address":"172.10.1.72","subscriptions":["all"],"version":"0.17.2","timestamp":1430864846},"check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1430882350,"executed":1430882350,"output":"No keepalive sent from client for 17504 seconds (>=180)","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":574,"action":"create"},{"id":"2cf2065c-066e-4458-952f-a5a36b85389f","client":{"name":"Node01","address":"172.10.1.63","subscriptions":["all"],"version":"0.17.2","timestamp":1430881368},"check":{"type":"metric","command":"/etc/sensu/plugins/memory-metrics-percent.rb","interval":10,"subscribers":["all"],"handlers":["relay"],"name":"memory-metrics","issued":1430881378,"executed":1430881378,"duration":0.01,"output":"sh: 1: /etc/sensu/plugins/memory-metrics-percent.rb: not found\n","status":127,"history":["127","127","127","127","127"],"total_state_change":0},"occurrences":5,"action":"create"},{"id":"797fc3c7-f1f1-4224-8907-c7c3482fff18","client":{"name":"Node01","address":"172.10.1.63","subscriptions":["all"],"version":"0.17.2","timestamp":1430881368},"check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1430882350,"executed":1430882350,"output":"No keepalive sent from client for 982 seconds (>=180)","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":27,"action":"create"},{"id":"b6e0059a-3c80-47d7-b45d-6b6c8b19aa67","client":{"name":"4-C2C-Node01","address":"172.10.1.63","subscriptions":["all"],"version":"0.17.2","timestamp":1430880993},"check":{"type":"metric","command":"/etc/sensu/plugins/memory-metrics-percent.rb","interval":10,"subscribers":["all"],"handlers":["relay"],"name":"memory-metrics","issued":1430881008,"executed":1430881008,"duration":0.01,"output":"sh: 1: /etc/sensu/plugins/memory-metrics-percent.rb: not found\n","status":127,"history":["127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127","127"],"total_state_change":0},"occurrences":2968,"action":"create"},{"id":"261d07f2-39fc-419c-9ea3-0a2f8d1eeea4","client":{"name":"4-C2C-Node01","address":"172.10.1.63","subscriptions":["all"],"version":"0.17.2","timestamp":1430880993},"check":{"thresholds":{"warning":120,"critical":180},"name":"keepalive","issued":1430882350,"executed":1430882350,"output":"No keepalive sent from client for 1357 seconds (>=180)","status":2,"history":["2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2","2"],"total_state_change":0},"occurrences":40,"action":"create"}]ro
```

Could you help me please to troubleshoot it ?

Thank you

**Comment by lfrancois** [comment]
It looks like an issue with the version of ruby we used. I kind of fixed sensu.rb job doing this:

```
root@panoramix:~/sweet_dashboard_project/jobs# diff -u sensu.rb.orig sensu.rb
--- sensu.rb.orig       2015-05-06 09:26:45.345205686 +0200
+++ sensu.rb    2015-05-06 09:26:50.165144861 +0200
@@ -18,12 +18,11 @@
   client_critical = Array.new
   auth = (SENSU_API_USER.empty? || SENSU_API_PASSWORD.empty?) ? false : true
 
-  uri = URI(SENSU_API_ENDPOINT+"/events")
-  req = Net::HTTP::Get.new(uri)
+  uri = URI.parse(SENSU_API_ENDPOINT+"/events")
+  req = Net::HTTP.new(uri.host, uri.port)
   req.basic_auth SENSU_API_USER, SENSU_API_PASSWORD if auth
-  response = Net::HTTP.start(uri.hostname, uri.port) {|http|
-    http.request(req)
-  }
+  response = req.get(uri.request_uri)
+  puts response.body
 
   warn = Array.new
   crit = Array.new
@@ -62,4 +61,5 @@
   send_event('sensu-warn-list', { items: client_warning })
   send_event('sensu-crit-list', { items: client_critical })
 
 end
root@panoramix:~/sweet_dashboard_project/jobs# 
```

**Comment by jszaszvari** [comment]
Exact same issue here with a fresh install and nothing custom.

LSB Version:    :base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID: CentOS
Description:    CentOS release 6.6 (Final)
Release:        6.6
Codename:       Final


scheduler caught exception:
undefined method `empty?' for #<URI::HTTP:0x00000003a316c0 URL:http://localhost:4567/events>
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:1861:in `initialize'
/usr/local/rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/net/http.rb:2094:in `initialize'
/root/ptips_dash/jobs/sensu.rb:22:in `new'
/root/ptips_dash/jobs/sensu.rb:22:in `block in <top (required)>'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:230:in `trigger_block'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/jobs.rb:204:in `block in trigger'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `call'
/usr/local/rvm/gems/ruby-1.9.3-p551/gems/rufus-scheduler-2.0.24/lib/rufus/sc/scheduler.rb:430:in `block in trigger_job'

**Comment by mrichar1** [comment]
Apologies that this has sat so long unresolved!

I've just re-tested the current code against ruby 2.1.5 and 2.3.1 (with and without authentication) and I'm not seeing any of these problems.

I'm going to mark this issue as closed, as I suspect few people are now using ruby <2.x - but feel free to fire up a new issue with new debugging if you're still having problems with a newer ruby...
